#!/bin/sh

# Copyright 2023 Google LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Format Terraform 
terragrunt hcl fmt
terraform fmt -recursive 

# Format and tidy go
find ./modules -type f -name "*.go" | xargs -I {} dirname {} | sort -u | while read -r dir; do
  echo "Running 'go fmt' on $dir"
  (cd "$dir" && go fmt && go mod tidy)
done

# Keep module docs up to date
for d in modules/*; do
  if terraform-docs md "$d" > "$d/README.md"; then
    git add "./$d/README.md"
  fi
done

# Generate Terragrunt / Terraform module dependecy graph
terragrunt dag graph  | dot -Tpng > assets/module-dependenceis.png
